
version: 2
jobs:
  build:
    docker:
      - image: docker:stable
        environment:
          DOCKER_BUILDKIT: "1"  # Enable Docker BuildKit
    steps:
      - run:
          name: pre
          command: |
            apk add --no-progress git jq curl make
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t amanoese/dockerx-ex .
            ##- run:
            ##    name: Buildx Docker image
            ##    command: |
            ##      docker buildx build --platform linux/amd64,linux/arm64 -t amanoese/dockerx-ex --local .
